defaults: &defaults
  working_directory: ~/markovmodel/PyEMMA
  docker:
    - image: continuumio/miniconda3

inst_conda_bld: &inst_conda_bld
  - run: conda config --add channels conda-forge
  - run: conda config --set always_yes true
  - run: conda config --set quiet true
  - run: conda install conda-build

version: 2

jobs:
  build:
    <<: *defaults
    parallelism: 1
    steps:
      - checkout
      - run: git fetch --unshallow || true
      - run: apt-get install -y cpp gcc
      - run: apt-get install -y libx11-6 python-dev git build-essential
      - run: apt-get install -y autoconf automake gcc g++ make gfortran
      - run: apt-get install -y python-tables
      - run: apt-get install -y libhdf5-serial-dev

      - run: conda config --add channels conda-forge
      - run: conda config --set always_yes true
      - run: conda config --set quiet true
      - run: conda install conda-build
      - run: which pip
      - run: conda install scipy;
      - run: conda install numpy;
      - run: conda install numba;
      - run: conda install dask;
      - run: pip install tables
      - run: pip install pip --upgrade; 
      - run: pip install -e .
      - run: pip install coverage
      - run: git clone -b neuronunit https://github.com/russelljjarvis/jit_hub.git
      - run: cd jit_hub; pip install -e .; cd ..;
      - run: pip install cython
      - run: pip install asciiplotlib;
      - run: git clone -b master https://github.com/russelljjarvis/BluePyOpt.git
      - run: cd BluePyOpt; pip install -e .
      - run: pip install streamlit
      - run: pip install sklearn
      - run: pip install seaborn
      - run: pip install frozendict
      # - run: conda install hdf5
      # - run: conda install -c conda-forge pytables
      - run: pip install allensdk==0.16.3
      - run: cd BluePyOpt/unittest; python adexp_opt.py
      - run: cd BluePyOpt/unittest; coverage run adexp_opt.py
      - run: cd BluePyOpt/unittest; coverage report

  test:
    <<: *defaults
    parallelism: 1
    environment:
      PYTHONHASHSEED: 0
      OMP_NUM_THREADS: 1
      PYEMMA_NJOBS: 1

    steps:
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - run: conda config --add channels conda-forge
      - run: conda config --set always_yes true
      - run: conda config --set quiet true
      - run: apt-get install -y cpp gcc
      - run: apt-get install -y python-tables
      - run: apt-get install -y libx11-6 python-dev git build-essential
      - run: apt-get install -y autoconf automake gcc g++ make gfortran
      - run: conda install conda-build
      - run: conda install scipy;
      - run: pip install tables
      - run: pip install git+https://github.com/russelljjarvis/jit_hub.git@neuronunit
      - run: apt-get update
      - run: pip install pip --upgrade; pip install -r requirements.txt;
      - run: pip install -e .
      - run: python unittest/latest_file_adexp.py
      - run: pip install coverage
      - run: coverage run unittest/latest_file_adexp.py
      - run: coverage report
